name: Update DIP21 Daten (Weekly all)

on:
  schedule:
    - cron: "0 0 * * MON"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Scrape Data
        run: npx @democracy-deutschland/dip21-scraper --html -s 10 --periods Alle --operationtypes Alle --quiet --out .
        env:
          SCRAPER_USER_AGEND: github.com/bundestag/dip21-daten#weekly

      - run: git status

      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Action – Daily Update DIP21 Data
